coredata: add missing EnvironmentException import
Fixes:
NameError: name 'EnvironmentException' is not defined

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>