cargo: improve error message for dependency version conflicts
While developing I often got a confusing 'Neither a subproject directory nor
a None.wrap file was found'.  Replace it with a clear message that explains:

1. Which dependency couldn't be found
2. What versions are available in the root Cargo.lock
3. That this is likely a version conflict
4. How to fix it (update dependencies to match root Cargo.lock)

Example:
ERROR: Dependency 'socket2-0.4-rs' not found. Root Cargo.lock provides:
socket2-0.5-rs, socket2-0.6-rs. This could be a Meson bug, please report it.

I am actually not sure if this is really always a Meson bug.  But to be
safe, suggest reporting it until more experience is gained.

Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>