actually do pass encoding to file I/O
It was proposed to be added, but then questioned and removed in
https://github.com/mesonbuild/meson/pull/15086#discussion_r2405334384

> I'm not sure this is correct. IIUC, this file is passed as a
> configuration file to bash thus it needs to be written with the system
> encoding, which in Python should be what you get when encoding is not
> specified.

It is insane(ly broken) to use a non-ascii-compatible encoding, and we
exclusively write ascii. We also test in CI that the encoding= argument
is *explicitly* passed, and we do so precisely because python 3.15
changes the meaning of `encoding=None` from "system encoding" to
"utf-8", so in the most absolute sense, it is simply wrong to review an
`encoding=` PR and say to remove the encoding to get the system
encoding.

The bash logic has had that problem forever; the zsh logic only since
the recent PR. Switch both to explicitly require utf-8, which is
ascii-compatible and everyone should use anyway.

Fixes:
```
Traceback (most recent call last):
  File ".../mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File ".../mesonbuild/mdevenv.py", line 226, in run
    tmprc = tempfile.NamedTemporaryFile(mode='w')
  File "/usr/lib/python3.13/tempfile.py", line 574, in NamedTemporaryFile
    encoding = _io.text_encoding(encoding)
EncodingWarning: 'encoding' argument not specified

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```