tests: when generating git repositories, make sure that pgpsign is off
I have a local configuration

tag.forcesignannotated=true
commit.gpgsign=true

This causes the tests to fail with e.g.

error: gpg failed to sign the data
fatal: failed to write commit object

Since this is a unittest, it is never wrong to tell git "just ignore
prior configuration, and disable all PGP signing".