Fix to avoid processing AIX_LINKER rule if not required.
When we do not want to archive we should not add the AIX_LINKER rule.

Else it will lead to an error like
return self.linker.get_command_to_archive_shlib()
AttributeError: 'NoneType' object has no attribute 'get_command_to_archive_shlib'

This commit fixes the same.