backend/ninja: pass language name instead of compiler
Traceback (most recent call last):
  File "F:\avian\meson\mesonbuild\mesonmain.py", line 289, in run
    app.generate()
  File "F:\avian\meson\mesonbuild\mesonmain.py", line 179, in generate
    g.generate(intr)
  File "F:\avian\meson\mesonbuild\backend\ninjabackend.py", line 185, in generate
    self.generate_rules(outfile)
  File "F:\avian\meson\mesonbuild\backend\ninjabackend.py", line 745, in generate_rules
    self.generate_compile_rules(outfile)
  File "F:\avian\meson\mesonbuild\backend\ninjabackend.py", line 1530, in generate_compile_rules
    self.generate_llvm_ir_compile_rule(compiler, True, outfile)
  File "F:\avian\meson\mesonbuild\backend\ninjabackend.py", line 1386, in generate_llvm_ir_compile_rule
    ' '.join(self.get_cross_info_lang_args(compiler, is_cross)),
  File "F:\avian\meson\mesonbuild\backend\ninjabackend.py", line 1406, in get_cross_info_lang_args
    return self.environment.cross_info.config['properties'][lang + '_args']
TypeError: unsupported operand type(s) for +: 'ClangCCompiler' and 'str'

Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>