When subproject() fails because downloading is disabled, say what failed
It's not especially explanatory to say:

```
meson.build:357:34: ERROR: Automatic wrap-based subproject downloading is disabled
```

But if we instead say this:

```
ERROR: Subproject libsamplerate is buildable: NO

meson.build:357:34: ERROR: Automatic wrap-based subproject downloading is disabled
```

It becomes a lot clearer to casual inspection, why it failed. And it
matches the way we otherwise report errors for an unbuildable subproject
(configure errors).

Bug: https://github.com/jacktrip/jacktrip/issues/1380
(cherry picked from commit 8a9dea2e3745935d55201123288e529acede043e)