meson-test-run.xml: Replace characters which are illegal in XML
lxml is a lot more fussy about not stuffing random binary data into our
XML file, raising the following exception:

> ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

Replace characters which are illegal in XML with a printable
representation, by using the utility which exists in mtest for exactly
that purpose here as well.