Fix .travis.yml for updated OSX image
Since [1], OSX builds on travis fail with:

Error: Refusing to uninstall /usr/local/Cellar/python/3.6.5_1
because it is required by gdal, numpy, postgis, which are currently installed.

Revise #3163

[1] https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce