cargo: set edition for build machine as well
This fixes compilation of glib-macros-0.20.4:

error[E0405]: cannot find trait `TryFrom` in this scope
  --> ../subprojects/glib-macros-0.20.4/src/clone.rs:22:10
   |
22 | impl<'a> TryFrom<&'a Ident> for CaptureKind {
   |          ^^^^^^^ not found in this scope
   |
   = note: 'std::convert::TryFrom' is included in the prelude starting in Edition 2021
help: consider importing this trait
   |
3  + use std::convert::TryFrom;
   |

Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 7c2f22feefe2d8014138b02a2119026a01f52dea)