Add a testing case for a decimal number with a leading zero
That syntax is invalid, since decimal numbers should never have a
leading zero and octal numbers use the `0o` prefix instead.

This matches Python 3 syntax which does not accept it:

  $ python3
  >>> 0123
    File "<stdin>", line 1
      0123
         ^
  SyntaxError: invalid token
  >>>

Add a "failing" test case to confirm this property is preserved and no
regressions are introduced in this area.