baseplatformtests: Don't specify "/" in os.path.join
This is needed because otherwise, if while MSYSTEM= python run_unittests.py PlatformAgnosticTests.test_error_configuring_subdir in msys2, I was getting this error:
```
$ MSYSTEM= python run_unittests.py PlatformAgnosticTests.test_error_configuring_subdir
Meson build system 1.12.0.rc2 Unit Tests
pytest not found, using unittest instead
F
Stdout:
$ C:\msys64\mingw64\bin\python.exe C:\Users\moi15moi\Documents\GitHub\meson\meson.py setup --backend=ninja --prefix /usr --libdir lib C:\Users\moi15moi\Documents\GitHub\meson\tmp2judbrrm "C:\Users\moi15moi\Documents\GitHub\meson\test cases/common\152 index customtarget\subdir"
stdout:
The Meson build system
Version: 1.12.0.rc2
Source dir: C:\Users\moi15moi\Documents\GitHub\meson\test cases\common\152 index customtarget\subdir
Build dir: C:\Users\moi15moi\Documents\GitHub\meson\tmp2judbrrm
Build type: native build

ERROR: Not the project root: first statement must be a call to project()

Did you mean to run meson from the directory: "C:\Users\moi15moi\Documents\GitHub\meson\test cases\common\152 index customtarget"?

A full log can be found at C:\Users\moi15moi\Documents\GitHub\meson\tmp2judbrrm\meson-logs\meson-log.txt

======================================================================
FAIL: test_error_configuring_subdir (unittests.platformagnostictests.PlatformAgnosticTests.test_error_configuring_subdir)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\moi15moi\Documents\GitHub\meson\unittests\platformagnostictests.py", line 422, in test_error_configuring_subdir
    self.assertIn(f'Did you mean to run meson from the directory: "{testdir}"?', out)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'Did you mean to run meson from the directory: "C:\\Users\\moi15moi\\Documents\\GitHub\\meson\\test cases/common\\152 index customtarget"?' not found in 'Build started at 2026-08-04T19:25:58.484065\nMain binary: C:\\msys64\\mingw64\\bin\\python.exe\nBuild Options: -Dbackend=ninja -Dprefix=/usr -Dlibdir=lib\nPython system: Window
s\nThe Meson build system\nVersion: 1.12.0.rc2\nSource dir: C:\\Users\\moi15moi\\Documents\\GitHub\\meson\\test cases\\common\\152 index customtarget\\subdir\nBuild dir: C:\\Users\\moi15moi\\Documents\\GitHub\\meson\\tmp2judbrrm\nBuild type: native build\n\nERROR: Not the project root: first statement must be a call to project()\n\nDid you mean
 to run meson from the directory: "C:\\Users\\moi15moi\\Documents\\GitHub\\meson\\test cases\\common\\152 index customtarget"?\n'

Stdout:
$ C:\msys64\mingw64\bin\python.exe C:\Users\moi15moi\Documents\GitHub\meson\meson.py setup --backend=ninja --prefix /usr --libdir lib C:\Users\moi15moi\Documents\GitHub\meson\tmp2judbrrm "C:\Users\moi15moi\Documents\GitHub\meson\test cases/common\152 index customtarget\subdir"
stdout:
The Meson build system
Version: 1.12.0.rc2
Source dir: C:\Users\moi15moi\Documents\GitHub\meson\test cases\common\152 index customtarget\subdir
Build dir: C:\Users\moi15moi\Documents\GitHub\meson\tmp2judbrrm
Build type: native build

ERROR: Not the project root: first statement must be a call to project()

Did you mean to run meson from the directory: "C:\Users\moi15moi\Documents\GitHub\meson\test cases\common\152 index customtarget"?

A full log can be found at C:\Users\moi15moi\Documents\GitHub\meson\tmp2judbrrm\meson-logs\meson-log.txt

----------------------------------------------------------------------
Ran 1 test in 0.479s

FAILED (failures=1)
Total time: 0.787 seconds
```

The msys2 CI doesn't catch this issue currently because PlatformAgnosticTests are skipped (https://github.com/mesonbuild/meson/blob/f004d10e758073a5aa15b195e7047f5c662f5581/unittests/platformagnostictests.py#L25)

Part-of: https://github.com/mesonbuild/meson/pull/16073
Closes: https://github.com/mesonbuild/meson/pull/16073
Signed-off-by: Sam James <sam@gentoo.org>
(cherry picked from commit ee72484e8f594a709e20e4ca06a9246c36862b32)