Added methods to add post arguments: add_global_post_link_arguments add_project_post_link_arguments
Ie: "-ldl -lthread" need to be after the build path to avoid errors like:
undefined reference to `pthread_mutexattr_init'
undefined reference to `dlopen'