Fix run_project_test.py when not under CI
Since 492afe50, detect_ninja() returns a List[str], not a str.

run_project_test.py still happens to work under CI, as we bypass
detect_ninja(), but fails when run locally, as we try to exec() that list.

> Checking that building works...
> Traceback (most recent call last):
>   File "./run_project_tests.py", line 1301, in <module>
>     check_meson_commands_work(options)
>   File "./run_project_tests.py", line 1190, in check_meson_commands_work
>     pc, o, e = Popen_safe(compile_commands + dir_args, cwd=build_dir)
>   File "/wip/meson/mesonbuild/mesonlib.py", line 1220, in Popen_safe
>     stdout=stdout, stderr=stderr, **kwargs)
>   File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.6/subprocess.py", line 1278, in _execute_child
>     executable = os.fsencode(executable)
>   File "/usr/lib/python3.6/os.py", line 800, in fsencode
>     filename = fspath(filename)  # Does type-checking of `filename`.
> TypeError: expected str, bytes or os.PathLike object, not list