Fix formatting in mixed library error message
Python doesn't permit mixing manual field specification and automatic
field numbering, so move everything to automatic (and re-order args to
match).

        target = targetclass(name, self.subdir, self.subproject, for_machine, sources, objs, self.environment, kwargs)
      File "/home/cody/d/meson/mesonbuild/build.py", line 1425, in __init__
        super().__init__(name, subdir, subproject, for_machine, sources, objects, environment, kwargs)
      File "/home/cody/d/meson/mesonbuild/build.py", line 469, in __init__
        self.process_kwargs(kwargs, environment)
      File "/home/cody/d/meson/mesonbuild/build.py", line 854, in process_kwargs
        self.add_deps(deplist)
      File "/home/cody/d/meson/mesonbuild/build.py", line 1017, in add_deps
        self.link(l)
      File "/home/cody/d/meson/mesonbuild/build.py", line 1065, in link
        msg = 'Tried to mix libraries for machines {1} and {2} in target {!r}'.format(self.name, self.for_machine, t.for_machine)
    ValueError: cannot switch from manual field specification to automatic field numbering