add type annotations to mesonmain
An oddity: sys.stdout is statically defined as type TextIO instead of
TextIOWrapper, and thus doesn't have a .reconfigure method. This is
because they expect people to override sys.stdout with other objects,
which we do not do. Instead, assume it is always correct.

There are two final errors due to metaprogramming:
```
mesonbuild/mesonmain.py:196:13: error: Returning Any from function declared to return "int"  [no-any-return]
mesonbuild/mesonmain.py:225:9: error: Returning Any from function declared to return "int"  [no-any-return]
```