test cases/common/32 has header: disable undef with libcxx
Can be tested with adding -stdlib=libc++ to C++ flags.

    In file included from /usr/include/c++/v1/stdio.h:93:
    In file included from /usr/include/c++/v1/__config:14:
    In file included from /usr/include/c++/v1/__configuration/abi.h:15:
    /usr/include/c++/v1/__configuration/platform.h:35:7: error: function-like macro '__has_include' is not defined
       35 | #  if __has_include(<features.h>)
          |       ^
    /usr/include/c++/v1/__configuration/platform.h:48:5: error: function-like macro '__has_include' is not defined
       48 | #if __has_include(<picolibc.h>)
          |     ^
    1 warning and 2 errors generated.
    '

(cherry picked from commit dba1008ffee2392129f205c00d526073ff5b24c3)