msetup: fix misleading error message about directories
`validate_core_dirs` method is used to find out which directory contains the
sources and which one will be used as build directory.

Its error message misleads the user when the user follows the order of
positional arguments of `meson setup` (the first one should be the build
directory and the second one the source directory). In case of invalid
configuration, e.g. when neither directory contained a `meson.build` file, the
error message was:

> $ meson setup ./build ./src
> ERROR: Neither source directory './build' nor build directory './src' contain
> a build file meson.build.

In this case, a user might waste time trying to figure out why their build
directory is being reported as the source directory.

Since the purpose of this method is to determine what each directory
corresponds, the best possible error message should make no assumptions about
the directories.