devenv: Don't use Path.relative_to() to resolve relative paths
It's utterly broken, and only works when one path is inside the other:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/mdevenv.py", line 188, in run
    write_gdb_script(privatedir, install_data, workdir)
  File "/usr/lib/python3.12/site-packages/mesonbuild/mdevenv.py", line 142, in write_gdb_script
    rel_path = gdbinit_path.relative_to(workdir_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: '/path/to/builddir/.gdbinit' is not in the subpath of '/path/to/workdir'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

(cherry picked from commit 069d89223769a380ccecd069a01e3bd5d71fdef3)