fix python traceback when gtkdoc needs an exe_wrapper but doesn't have one
In commit c88bfdbefc2f79ac2dfa9bff5847c350de5f5db8 we added support for
an exe_wrapper to gtkdoc, which checked twice whether the environment
says it is needed, and didn't check at all whether one was provided.

The result:

  File "/usr/lib/python3/dist-packages/mesonbuild/modules/gnome.py", line 1354, in gtkdoc
    t_args.append('--run=' + ' '.join(state.environment.get_exe_wrapper().get_command()))
AttributeError: 'NoneType' object has no attribute 'get_command'

Instead, check whether we have a valid exe_wrapper (if we don't need
one, then even when one is defined in the cross file, we get an
EmptyExternalProgram) and if we do, use it.

If we don't have one, but need one, then we revert back to the behavior
before commit c88bfdbefc2f79ac2dfa9bff5847c350de5f5db8, which probably
means "executing the doc target causes the command to error out with
"Exec format error".