gnome: fix sources in gir target generation
Source for the gir_dep should be added to the GirTarget inputs
instead of the dependencies.

Traceback (most recent call last):
  File "/Users/andoni/git/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
  File "/Users/andoni/git/meson/mesonbuild/msetup.py", line 309, in run
    app.generate()
  File "/Users/andoni/git/meson/mesonbuild/msetup.py", line 186, in generate
    self._generate(env)
  File "/Users/andoni/git/meson/mesonbuild/msetup.py", line 250, in _generate
    intr.backend.generate()
  File "/Users/andoni/git/meson/mesonbuild/backend/ninjabackend.py", line 614, in generate
    self.generate_target(t)
  File "/Users/andoni/git/meson/mesonbuild/backend/ninjabackend.py", line 801, in generate_target
    self.generate_custom_target(target)
  File "/Users/andoni/git/meson/mesonbuild/backend/ninjabackend.py", line 1104, in generate_custom_target
    for output in d.get_outputs():
AttributeError: 'File' object has no attribute 'get_outputs'