travis.yml: Try to fix brew error:
Error: Refusing to uninstall /usr/local/Cellar/python/2.7.14
because it is required by mercurial 4.4, which is currently installed.