tests/common/134: Rename copy.py to copyfile.py
On some distros, running this causes Python to find the file itself as
the implementation of the `copy` module:

$ python3 copy.py
Traceback (most recent call last):
  File "copy.py", line 4, in <module>
    import shutil
  File "/usr/lib/python3.4/shutil.py", line 14, in <module>
    import tarfile
  File "/usr/lib/python3.4/tarfile.py", line 48, in <module>
    import copy
  File "/c/Users/nirbheek/projects/meson.git/test cases/common/134 generated llvm ir/copy.py", line 6, in <module>
    shutil.copyfile(sys.argv[1], sys.argv[2])
AttributeError: 'module' object has no attribute 'copyfile'