cargo: show nice error if a package is missing
Otherwise this would cause an

    AttributeError: 'NoneType' object has no attribute 'required_deps'

Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>