mtest: Use Popen_safe to run tests
Without this, we won't always decode the stdout properly before
printing it, which will cause a `UnicodeEncodeError`:

```py
Traceback (most recent call last):
  File "c:\python\lib\site-packages\mesonbuild\mesonmain.py", line 129, in run
    return options.run_func(options)
  File "c:\python\lib\site-packages\mesonbuild\mtest.py", line 1045, in run
    return th.doit()
  File "c:\python\lib\site-packages\mesonbuild\mtest.py", line 802, in doit
    self.run_tests(tests)
  File "c:\python\lib\site-packages\mesonbuild\mtest.py", line 954, in run_tests
    self.drain_futures(futures)
  File "c:\python\lib\site-packages\mesonbuild\mtest.py", line 969, in drain_futures
    result.result()
  File "c:\python\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "c:\python\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "c:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\python\lib\site-packages\mesonbuild\mtest.py", line 494, in run
    return self._run_cmd(wrap + cmd + self.test.cmd_args + self.options.test_args)
  File "c:\python\lib\site-packages\mesonbuild\mtest.py", line 625, in _run_cmd
    print(stdo, end='')
  File "c:\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 353: character maps to <undefined>
```

Found at https://github.com/ebassi/graphene/pull/197#discussion_r470028540
where `PYTHONIOENCODING=utf-8` had to be set in the env to fix it.