compilers: avoid -Wunused-value compiler warning in CLikeCompiler.has_type()
Otherwise, `CFLAGS='-Wall -Werror' meson build` can fail detection:

  Running compile:
  Working directory:  ./project/build/meson-private/tmpk86bgc04
  Code:
   #include <sys/types.h>
          void bar(void) {
              sizeof(loff_t);
          }
  -----------
  Command line: `cc ./project/build/meson-private/tmpk86bgc04/testfile.c -o ./project/build/meson-private/tmpk86bgc04/output.obj -c -Werror -Wall -D_FILE_OFFSET_BITS=64 -O0 -std=gnu99` -> 1
  stderr:
  ./project/build/meson-private/tmpk86bgc04/testfile.c: In function 'bar':
  ./project/build/meson-private/tmpk86bgc04/testfile.c:3:13: error: statement with no effect [-Werror=unused-value]
      3 |             sizeof(loff_t);
        |             ^~~~~~
  cc1: all warnings being treated as errors
  -----------
  Checking for type "loff_t" : NO

(cherry picked from commit fa8bd9306c01a1268d1a4cd7417ad753b1aa09e1)